require "Items/ProceduralDistributions"
-- 63Type2VanTire
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.63Type2VanTire");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.63Type2VanTire");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.2);
-- 63Type2VanMudflaps0
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.63Type2VanMudflaps0");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.63Type2VanMudflaps0");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.63Type2VanMudflaps0");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.1);
-- dasBootFull
table.insert(ProceduralDistributions.list["BarCounterLiquor"].items, "Base.dasBootFull");
table.insert(ProceduralDistributions.list["BarCounterLiquor"].items, 21);
table.insert(ProceduralDistributions.list["BarShelfLiquor"].items, "Base.dasBootFull");
table.insert(ProceduralDistributions.list["BarShelfLiquor"].items, 19);
table.insert(ProceduralDistributions.list["BinBar"].items, "Base.dasBootEmpty");
table.insert(ProceduralDistributions.list["BinBar"].items, 10);