require "Items/ProceduralDistributions"

--    /************************ FRAMES ************************/

-- Regular Frame
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.BicycleFrameRegular")
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.6)
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.BicycleFrameRegular")
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.6)
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.BicycleFrameRegular")
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.6)
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.BicycleFrameRegular")
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.6)
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.BicycleFrameRegular")
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.6)
-- Regular Frame Scrap
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.BicycleFrameRegularScrap")
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.6)
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.BicycleFrameRegularScrap")
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.6)
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.BicycleFrameRegularScrap")
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.6)
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.BicycleFrameRegularScrap")
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.6)
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.BicycleFrameRegularScrap")
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.6)

-- MTB Frame
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.BicycleFrameMTB")
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.6)
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.BicycleFrameMTB")
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.6)
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.BicycleFrameMTB")
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.6)
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.BicycleFrameMTB")
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.6)
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.BicycleFrameMTB")
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.6)
-- MTB Frame Scrap
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.BicycleFrameMTBScrap")
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.6)
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.BicycleFrameMTBScrap")
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.6)
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.BicycleFrameMTBScrap")
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.6)
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.BicycleFrameMTBScrap")
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.6)
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.BicycleFrameMTBScrap")
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.6)

--    /************************ SUSPENSION ************************/

-- Regular Suspension
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.BicycleSuspensionRegular3")
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.8)
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.BicycleSuspensionRegular3")
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.8)
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.BicycleSuspensionRegular3")
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.8)
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.BicycleSuspensionRegular3")
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.8)
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.BicycleSuspensionRegular3")
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.8)
-- Regular Suspension Scrap
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.BicycleSuspensionRegularScrap3")
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.8)
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.BicycleSuspensionRegularScrap3")
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.8)
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.BicycleSuspensionRegularScrap3")
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.8)
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.BicycleSuspensionRegularScrap3")
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.8)
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.BicycleSuspensionRegularScrap3")
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.8)

-- MTB Suspension
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.BicycleSuspensionMTB3")
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.8)
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.BicycleSuspensionMTB3")
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.8)
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.BicycleSuspensionMTB3")
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.8)
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.BicycleSuspensionMTB3")
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.8)
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.BicycleSuspensionMTB3")
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.8)
-- MTB Suspension Scrap
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.BicycleSuspensionMTBScrap3")
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.8)
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.BicycleSuspensionMTBScrap3")
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.8)
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.BicycleSuspensionMTBScrap3")
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.8)
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.BicycleSuspensionMTBScrap3")
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.8)
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.BicycleSuspensionMTBScrap3")
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.8)


--    /************************ BRAKES ************************/

-- Regular Brakes
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.BicycleBrakesRegular3")
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.8)
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.BicycleBrakesRegular3")
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.8)
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.BicycleBrakesRegular3")
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.8)
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.BicycleBrakesRegular3")
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.8)
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.BicycleBrakesRegular3")
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.8)
-- Regular Brakes Scrap
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.BicycleBrakesRegularScrap3")
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.8)
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.BicycleBrakesRegularScrap3")
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.8)
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.BicycleBrakesRegularScrap3")
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.8)
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.BicycleBrakesRegularScrap3")
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.8)
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.BicycleBrakesRegularScrap3")
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.8)

-- MTB Brakes
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.BicycleBrakesMTB3")
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.8)
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.BicycleBrakesMTB3")
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.8)
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.BicycleBrakesMTB3")
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.8)
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.BicycleBrakesMTB3")
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.8)
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.BicycleBrakesMTB3")
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.8)
-- MTB Brakes Scrap
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.BicycleBrakesMTBScrap3")
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.8)
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.BicycleBrakesMTBScrap3")
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.8)
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.BicycleBrakesMTBScrap3")
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.8)
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.BicycleBrakesMTBScrap3")
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.8)
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.BicycleBrakesMTBScrap3")
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.8)

--    /************************ TIRES ************************/

-- Regular Tire
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.BicycleRegularTire")
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.8)
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.BicycleRegularTire")
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.8)
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.BicycleRegularTire")
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.8)
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.BicycleRegularTire")
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.8)
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.BicycleRegularTire")
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.8)
-- Regular Tire Scrap
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.BicycleRegularTireScrap")
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.8)
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.BicycleRegularTireScrap")
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.8)
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.BicycleRegularTireScrap")
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.8)
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.BicycleRegularTireScrap")
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.8)
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.BicycleRegularTireScrap")
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.8)

-- MTB Tire
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.BicycleMTBTire")
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.8)
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.BicycleMTBTire")
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.8)
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.BicycleMTBTire")
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.8)
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.BicycleMTBTire")
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.8)
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.BicycleMTBTire")
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.8)
-- MTB Tire Scrap
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.BicycleMTBTireScrap")
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.8)
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.BicycleMTBTireScrap")
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.8)
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.BicycleMTBTireScrap")
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.8)
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.BicycleMTBTireScrap")
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.8)
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.BicycleMTBTireScrap")
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.8)

--    /************************ MISC ************************/

-- Seat
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.BicycleSeat")
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.8)
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.BicycleSeat")
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.8)
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.BicycleSeat")
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.8)
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.BicycleSeat")
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.8)
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.BicycleSeat")
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.8)
-- Scrap Seat
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.BicycleSeatScrap")
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.8)
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.BicycleSeatScrap")
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.8)
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.BicycleSeatScrap")
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.8)
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.BicycleSeatScrap")
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.8)
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.BicycleSeatScrap")
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.8)

-- Basket
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.BicycleBasket3")
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.8)
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.BicycleBasket3")
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.8)
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.BicycleBasket3")
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.8)
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.BicycleBasket3")
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.8)
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.BicycleBasket3")
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.8)

-- Headlight
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.BicycleHeadlight3")
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.4)
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.BicycleHeadlight3")
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.4)
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.BicycleHeadlight3")
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.4)
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.BicycleHeadlight3")
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.4)
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.BicycleHeadlight3")
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.4)

-- Lock
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.BicycleLock")
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.3)
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.BicycleLock")
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.3)
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.BicycleLock")
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.3)
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.BicycleLock")
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.3)
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.BicycleLock")
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.3)

-- Magazine Vol. 1
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, "Base.BicyclesMagVol1")
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, 1.5)
table.insert(ProceduralDistributions.list["CrateMagazines"].items, "Base.BicyclesMagVol1")
table.insert(ProceduralDistributions.list["CrateMagazines"].items, 1.5)
table.insert(ProceduralDistributions.list["EngineerTools"].items, "Base.BicyclesMagVol1")
table.insert(ProceduralDistributions.list["EngineerTools"].items, 1.5)
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, "Base.BicyclesMagVol1")
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, 1.5)
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, "Base.BicyclesMagVol1")
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, 1.5)
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, "Base.BicyclesMagVol1")
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, 0.3)
table.insert(ProceduralDistributions.list["LibraryBooks"].items, "Base.BicyclesMagVol1")
table.insert(ProceduralDistributions.list["LibraryBooks"].items, 1.5)
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, "Base.BicyclesMagVol1")
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, 1.5)
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, "Base.BicyclesMagVol1")
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, 0.3)
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, "Base.BicyclesMagVol1")
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, 0.3)

-- Magazine Vol. 2
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, "Base.BicyclesMagVol2")
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, 1.5)
table.insert(ProceduralDistributions.list["CrateMagazines"].items, "Base.BicyclesMagVol2")
table.insert(ProceduralDistributions.list["CrateMagazines"].items, 1.5)
table.insert(ProceduralDistributions.list["EngineerTools"].items, "Base.BicyclesMagVol2")
table.insert(ProceduralDistributions.list["EngineerTools"].items, 1.5)
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, "Base.BicyclesMagVol2")
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, 1.5)
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, "Base.BicyclesMagVol2")
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, 1.5)
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, "Base.BicyclesMagVol2")
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, 0.3)
table.insert(ProceduralDistributions.list["LibraryBooks"].items, "Base.BicyclesMagVol2")
table.insert(ProceduralDistributions.list["LibraryBooks"].items, 1.5)
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, "Base.BicyclesMagVol2")
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, 1.5)
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, "Base.BicyclesMagVol2")
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, 0.3)
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, "Base.BicyclesMagVol2")
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, 0.3)

-- Magazine Vol. 3
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, "Base.BicyclesMagVol3")
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, 1.5)
table.insert(ProceduralDistributions.list["CrateMagazines"].items, "Base.BicyclesMagVol3")
table.insert(ProceduralDistributions.list["CrateMagazines"].items, 1.5)
table.insert(ProceduralDistributions.list["EngineerTools"].items, "Base.BicyclesMagVol3")
table.insert(ProceduralDistributions.list["EngineerTools"].items, 1.5)
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, "Base.BicyclesMagVol3")
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, 1.5)
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, "Base.BicyclesMagVol3")
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, 1.5)
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, "Base.BicyclesMagVol3")
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, 0.3)
table.insert(ProceduralDistributions.list["LibraryBooks"].items, "Base.BicyclesMagVol3")
table.insert(ProceduralDistributions.list["LibraryBooks"].items, 1.5)
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, "Base.BicyclesMagVol3")
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, 1.5)
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, "Base.BicyclesMagVol3")
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, 0.3)
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, "Base.BicyclesMagVol3")
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, 0.3)